/** Console definitions — all 13 stations from the design doc. */
export const CONSOLES = [
  {
    id: 'navigation',
    name: 'NAVIGATION',
    icon: '⊕',
    color: '#00aaff',
    desc: 'In-system piloting · compass heading · galactic jump targeting',
  },
  {
    id: 'short_range',
    name: 'SHORT RANGE SCAN',
    icon: '◎',
    color: '#44ffaa',
    desc: 'Local system scan · nearby objects · hazards · contacts',
  },
  {
    id: 'long_range',
    name: 'LONG RANGE SCAN',
    icon: '⊙',
    color: '#88ddff',
    desc: 'Galaxy-level scan · warp-range systems · stellar cartography',
  },
  {
    id: 'weapons',
    name: 'WEAPONS',
    icon: '◆',
    color: '#ff4444',
    desc: 'Offensive systems · laser targeting · missile management',
  },
  {
    id: 'shields',
    name: 'SHIELDS',
    icon: '❖',
    color: '#4488ff',
    desc: 'Defensive systems · shield strength · distribution',
  },
  {
    id: 'repairs',
    name: 'REPAIRS',
    icon: '✦',
    color: '#ffaa00',
    desc: 'Direct repair bots · damaged section triage · hull integrity',
  },
  {
    id: 'transportation',
    name: 'TRANSPORTATION',
    icon: '⇄',
    color: '#ff88cc',
    desc: 'Transport bots · cargo movement between rooms',
  },
  {
    id: 'manufacturing',
    name: 'MANUFACTURING',
    icon: '⬡',
    color: '#ffcc44',
    desc: 'Fabrication queue · manufacturing facility management',
  },
  {
    id: 'power',
    name: 'POWER',
    icon: '⚡',
    color: '#ffee00',
    desc: 'Power distribution · reactor output · battery management',
  },
  {
    id: 'engines',
    name: 'ENGINES',
    icon: '⚙',
    color: '#ff6600',
    desc: 'Engine output · thrust · warp drive control',
  },
  {
    id: 'life_support',
    name: 'LIFE SUPPORT',
    icon: '✚',
    color: '#44ffcc',
    desc: 'Air quality · temperature · habitat systems',
  },
  {
    id: 'comms',
    name: 'COMMUNICATIONS',
    icon: '◉',
    color: '#00ffcc',
    desc: 'Comms with ships and planets · signal intercept',
  },
  {
    id: 'mining',
    name: 'MINING OPS',
    icon: '◈',
    color: '#aa88ff',
    desc: 'Mining bot deployment · resource stockpile · extraction',
  },
]
