// Role rosters per crew size — derived from docs/05-stations-and-crew.md
// Each role lists the consoles available on that tablet. The first console
// listed is the role's PRIMARY station (shown first on the tab strip).

export const CREW_LAYOUTS = {
  4: [
    {
      id: 'captain_pilot',
      name: 'CAPTAIN / PILOT',
      icon: '⊕',
      color: '#00aaff',
      desc: 'Steer the ship, plot warp jumps, read incoming messages.',
      consoles: ['navigation', 'short_range', 'long_range', 'comms'],
    },
    {
      id: 'gunner',
      name: 'GUNNER',
      icon: '◆',
      color: '#ff4444',
      desc: 'Run weapons and shields together. Fire, lock, distribute power.',
      consoles: ['weapons', 'shields'],
    },
    {
      id: 'chief_engineer',
      name: 'CHIEF ENGINEER',
      icon: '⚡',
      color: '#ffee00',
      desc: 'Reactors, allocations, engines, life-support warnings.',
      consoles: ['power', 'engines', 'life_support'],
    },
    {
      id: 'bosun',
      name: 'BOSUN',
      icon: '✦',
      color: '#ffaa00',
      desc: 'Repairs, manufacturing, transport, mining — bot wrangler.',
      consoles: ['repairs', 'manufacturing', 'transportation', 'mining'],
    },
  ],

  5: [
    {
      id: 'captain',
      name: 'CAPTAIN / COMMS',
      icon: '◉',
      color: '#00ffcc',
      desc: 'Long-range scans, communications, mission decisions.',
      consoles: ['comms', 'long_range', 'short_range'],
    },
    {
      id: 'pilot',
      name: 'PILOT',
      icon: '⊕',
      color: '#00aaff',
      desc: 'Navigation and engine control. Owns warp execution.',
      consoles: ['navigation', 'engines'],
    },
    {
      id: 'tactical',
      name: 'TACTICAL',
      icon: '◆',
      color: '#ff4444',
      desc: 'Weapons + shields combined.',
      consoles: ['weapons', 'shields'],
    },
    {
      id: 'engineer',
      name: 'ENGINEER',
      icon: '⚡',
      color: '#ffee00',
      desc: 'Reactor & power distribution; life-support monitoring.',
      consoles: ['power', 'life_support'],
    },
    {
      id: 'bosun',
      name: 'BOSUN',
      icon: '✦',
      color: '#ffaa00',
      desc: 'Repairs, manufacturing, transport, mining.',
      consoles: ['repairs', 'manufacturing', 'transportation', 'mining'],
    },
  ],

  6: [
    {
      id: 'captain',
      name: 'CAPTAIN',
      icon: '◉',
      color: '#00ffcc',
      desc: 'Comms and galaxy oversight.',
      consoles: ['comms', 'long_range'],
    },
    {
      id: 'pilot',
      name: 'PILOT',
      icon: '⊕',
      color: '#00aaff',
      desc: 'Navigation with local scan for tactical awareness.',
      consoles: ['navigation', 'short_range'],
    },
    {
      id: 'weapons',
      name: 'WEAPONS OFFICER',
      icon: '◆',
      color: '#ff4444',
      desc: 'Targeting and offensive fire.',
      consoles: ['weapons'],
    },
    {
      id: 'shields',
      name: 'SHIELDS OFFICER',
      icon: '❖',
      color: '#4488ff',
      desc: 'Defense lasers, shield batteries, hull‑section power.',
      consoles: ['shields'],
    },
    {
      id: 'engineer',
      name: 'ENGINEER',
      icon: '⚡',
      color: '#ffee00',
      desc: 'Power, engines, and life-support warnings.',
      consoles: ['power', 'engines', 'life_support'],
    },
    {
      id: 'bosun',
      name: 'BOSUN',
      icon: '✦',
      color: '#ffaa00',
      desc: 'Repairs, manufacturing, transport, mining.',
      consoles: ['repairs', 'manufacturing', 'transportation', 'mining'],
    },
  ],

  8: [
    {
      id: 'captain',
      name: 'CAPTAIN',
      icon: '◉',
      color: '#00ffcc',
      desc: 'Comms and galaxy oversight.',
      consoles: ['comms', 'long_range'],
    },
    {
      id: 'pilot',
      name: 'PILOT',
      icon: '⊕',
      color: '#00aaff',
      desc: 'Navigation only — full focus on heading and warp.',
      consoles: ['navigation'],
    },
    {
      id: 'sensors',
      name: 'SENSORS',
      icon: '◎',
      color: '#44ffaa',
      desc: 'Short and long range scanning.',
      consoles: ['short_range', 'long_range'],
    },
    {
      id: 'weapons',
      name: 'WEAPONS OFFICER',
      icon: '◆',
      color: '#ff4444',
      desc: 'Targeting and offensive fire.',
      consoles: ['weapons'],
    },
    {
      id: 'shields',
      name: 'SHIELDS OFFICER',
      icon: '❖',
      color: '#4488ff',
      desc: 'Defense lasers, shield batteries, hull‑section power.',
      consoles: ['shields'],
    },
    {
      id: 'power_engineer',
      name: 'POWER ENGINEER',
      icon: '⚡',
      color: '#ffee00',
      desc: 'Reactor heat, output, and station allocation.',
      consoles: ['power', 'life_support'],
    },
    {
      id: 'propulsion_engineer',
      name: 'PROPULSION ENGINEER',
      icon: '⚙',
      color: '#ff6600',
      desc: 'Engines and warp-drive charging.',
      consoles: ['engines'],
    },
    {
      id: 'bosun',
      name: 'BOSUN',
      icon: '✦',
      color: '#ffaa00',
      desc: 'Repairs, manufacturing, transport, mining.',
      consoles: ['repairs', 'manufacturing', 'transportation', 'mining'],
    },
  ],

  10: [
    {
      id: 'captain',
      name: 'CAPTAIN',
      icon: '◉',
      color: '#00ffcc',
      desc: 'Communications and command.',
      consoles: ['comms'],
    },
    {
      id: 'pilot',
      name: 'PILOT',
      icon: '⊕',
      color: '#00aaff',
      desc: 'Navigation only.',
      consoles: ['navigation'],
    },
    {
      id: 'sensors',
      name: 'SENSORS',
      icon: '◎',
      color: '#44ffaa',
      desc: 'Short and long range scanning.',
      consoles: ['short_range', 'long_range'],
    },
    {
      id: 'weapons',
      name: 'WEAPONS OFFICER',
      icon: '◆',
      color: '#ff4444',
      desc: 'Targeting and offensive fire.',
      consoles: ['weapons'],
    },
    {
      id: 'shields',
      name: 'SHIELDS OFFICER',
      icon: '❖',
      color: '#4488ff',
      desc: 'Defense lasers, shield batteries, hull‑section power.',
      consoles: ['shields'],
    },
    {
      id: 'power_engineer',
      name: 'POWER ENGINEER',
      icon: '⚡',
      color: '#ffee00',
      desc: 'Reactor and power distribution.',
      consoles: ['power', 'life_support'],
    },
    {
      id: 'propulsion_engineer',
      name: 'PROPULSION ENGINEER',
      icon: '⚙',
      color: '#ff6600',
      desc: 'Engines and warp-drive charging.',
      consoles: ['engines'],
    },
    {
      id: 'damage_control',
      name: 'DAMAGE CONTROL',
      icon: '✦',
      color: '#ffaa00',
      desc: 'Repair-bot dispatch and triage.',
      consoles: ['repairs'],
    },
    {
      id: 'quartermaster',
      name: 'QUARTERMASTER',
      icon: '⬡',
      color: '#ffcc44',
      desc: 'Manufacturing and transport.',
      consoles: ['manufacturing', 'transportation'],
    },
    {
      id: 'mining_foreman',
      name: 'MINING FOREMAN',
      icon: '◈',
      color: '#aa88ff',
      desc: 'Mining ops and pickup transport.',
      consoles: ['mining', 'transportation'],
    },
  ],
}

// Allowed crew sizes
export const ALLOWED_PLAYER_COUNTS = [4, 5, 6, 8, 10]
